[package]
name = "edge-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
futures-util = "0.3.21"
http = "0.2.8"
http-body = "0.4.5"
matchit = "0.5.0"
tower-service = "0.3.1"
